import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="px-8 bg-white dark:bg-black text-black dark:text-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 flex flex-col justify-center items-center">
        <h1 className="m-0 leading-5 text-6xl">
          Welcome to{" "}
          <a
            className="text-blue-600 text-center no-underline hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-16 leading-6 text-2xl text-center">
          Get started by editing{" "}
          <code className="bg-slate-50 dark:bg-slate-900 rounded p-3 text-lg font-mono">
            pages/index.tsx
          </code>
        </p>

        <div className="max-w-screen-md grid grid-cols-2 gap-8">
          <Card
            title="Documentation"
            href="https://nextjs.org/docs"
            description="Find in-depth information about Next.js features and API."
          />

          <Card
            title="Learn"
            href="https://nextjs.org/learn"
            description="Learn about Next.js in an interactive course with quizzes!"
          />

          <Card
            title="Examples"
            href="https://github.com/vercel/next.js/tree/canary/examples"
            description="Discover and deploy boilerplate example Next.js projects."
          />

          <Card
            title="Deploy"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className="flex flex-1 py-8 justify-center items-center border-t border-solid border-gray-200 dark:border-slate-800">
        <a
          className="flex grow justify-center items-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-4 ml-2">
            <Image
              className="dark:invert"
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}

type CardProps = { title: string; href: string; description: string };

function Card({ title, href, description }: CardProps) {
  return (
    <a
      className="p-6 text-left text-inherit no-underline border border-solid border-gray-200 dark:border-slate-800 rounded-lg hover:text-blue-600 hover:border-blue-600 active:text-blue-600 active:border-blue-600 focus:text-blue-600 focus:border-blue-600"
      href={href}
    >
      <h2 className="mb-4 text-2xl">{title} &rarr;</h2>
      <p className="m-0 text-xl leading-normal">{description}</p>
    </a>
  );
}
